version: '3.8'

services:
  aiit-csv-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # bindet das lokale Verzeichnis ./plots (erst erstellen!) in den Container
      - ./plots:/data/plots
